import { Clock3, ShieldAlert, ShieldCheck } from "lucide-react";
import ScoreRing from "./ScoreRing";
import SignalRow from "./SignalRow";
import { riskTone } from "../../lib/risk";
import { formatTime } from "../../lib/format";

export default function DecisionPanel({ result, decision, score, ruleScore, mlProbability, lastRun }) {
  const tone = riskTone(decision);

  return (
    <div className={`panel decision-panel ${tone}`}>
      <div className="panel-header">
        <div>
          <span className="section-kicker">02 / DECISION</span>
          <h2>Risk Verdict</h2>
        </div>
        {tone === "danger" ? <ShieldAlert size={21} /> : <ShieldCheck size={21} />}
      </div>

      <div className="decision-core">
        <ScoreRing score={score} />

        <div className="decision-copy">
          <span>FINAL DECISION</span>
          <strong>{decision.toUpperCase()}</strong>
          <small>{result ? "Decision generated by Sentinel Risk Fusion." : "Awaiting transaction analysis."}</small>
        </div>
      </div>

      <div className="decision-divider" />

      <SignalRow ruleScore={ruleScore} mlProbability={mlProbability} />

      <div className="decision-footer">
        <Clock3 size={15} />
        {lastRun ? `Analyzed ${formatTime(lastRun)}` : "No analysis executed yet"}
      </div>
    </div>
  );
}
